services:
  - type: web
    name: movie-recommendation-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-recommendation-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: movie-recommendation-redis
          type: redis 
          property: connectionString
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3

database:
  - name: movie-recommendation-db
    plan: free

additionalServices:
  - type: redis
    name: movie-recommendation-redis
    plan: free