# Generated by Django 5.2.4 on 2025-08-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='ratings',
            new_name='rating',
        ),
    ]
