# Generated by Django 5.2.4 on 2025-08-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_rename_ratings_movie_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['rating'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
    ]
