# Generated by Django 5.2.4 on 2025-08-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_favorite_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tmbd_id',
            new_name='tmdb_id',
        ),
    ]
